project:
  type: book
  output-dir: docs

book:
  title: "Guia de Tradução de conteúdos técnicos sobre R para Português Brasileiro"
  author: 
    - "Beatriz Milz"
    - "..."
  date: "2023-11-16"
  repo-url: https://github.com/cienciadedatos/guia-traducao-ptbr
  site-url: https://cienciadedatos.github.io/guia-traducao-ptbr/
  repo-branch: main
  repo-actions: [edit, issue]  
  chapters:
    - index.qmd
    - dados.qmd
    - orientacoes.qmd
    - part: "Traduções realizadas no GitHub"
      chapters:  
      - git-github.qmd
      - setup-traducao.qmd
      - ambiente-local-rstudio.qmd
    - part: "Traduções realizadas no Weblate"
      chapters:  
      - weblate.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true

editor: visual

lang: pt
language: "custom-pt-br.yml"