project:
  type: book
  output-dir: docs

book:
  title: "Guia de Tradução de conteúdos técnicos sobre R para Português Brasileiro"
  author: "..."
  date: "2023-11-16"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

lang: pt