project:
  type: book
  output-dir: docs

book:
  page-navigation: true
  title: "Guia de Tradução de conteúdos técnicos sobre R para Português Brasileiro"
  author: 
    - "Beatriz Milz"
    - "..."
  date: "2023-11-16"
  repo-url: https://github.com/cienciadedatos/guia-traducao-ptbr
  site-url: https://cienciadedatos.github.io/guia-traducao-ptbr/
  repo-branch: main
  repo-actions: [edit, issue]
  search: true
  chapters:
    - index.qmd
    - dados.qmd
    - orientacoes.qmd
          
    - part: "Traduzindo via GitHub"
      chapters:  
      - git-github.qmd
      - revisando-github.qmd   
      - setup-traducao.qmd
      - ambiente-local-rstudio.qmd
      - traduzindo-rstudio.qmd
      - incorporando-revisao.qmd
      

      
    - part: "Traduzindo via Weblate"
      chapters:  
      - weblate.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true

editor: visual

lang: pt
language: "custom-pt-br.yml"